### PR TITLE
code refactoring to improve readability and quality

### PR DESCRIPTION
**Pull request by jeeljasani**
refactor(Db_Controller): rename method/variable
refactor(Db_Controller): Extract method
refactor(DatabaseManager,DatabaseUtils): Introduce explaining variable
refactor(DatabaseUtils,FileUtils): move method
refactor(CommonBottomSheetManager): Extract class
refactor(DatabaseManager,DatabaseUtils): Pull-up Variable/Method

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
What do you think about this, @theftzoku?

**Comment by itariqco** [comment]
> What do you think about this, @theftzoku?

yeah, these things i mentioned already and also need focus on Database structure.

**Comment by CrazyMarvin** [comment]
> > What do you think about this, @theftzoku?
> 
> yeah, these things i mentioned already and also need focus on Database structure.

Thanks for checking. 👍

**Comment by CrazyMarvin** [comment]
Thanks for your help, @jeeljasani! 😘

**Pull request merged**
