### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [To Don't/To Don't](https://hosted.weblate.org/projects/todont/to-dont/).

It also includes following components:

* [To Don't/Metadata](https://hosted.weblate.org/projects/todont/metadata/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by OliverStunt** [comment]
Hello there, it's me. I'm new to GitHub, so please forgive me if I do sth here improperly - but not entirely new to translations 😄 
Just one last string seems to have some problems. I also translated the title, quite well I believe, but now I noticed other languages don't transalte it. If You wish it reversed, I'll gladly revisit it.
Feel free to contact me anywhere You find me!

**Comment by CrazyMarvin** [comment]
Thank you very much for your help, @OliverStunt! 😘

**Comment by CrazyMarvin** [comment]
I am not sure if a translated title is the best option or not. 😅

Which string is causing issues?

**Comment by OliverStunt** [comment]
Easiest to see on Weblate directly, the one with contact info. There is a formatting sign that I just can't copy, and apparently neither the other Polish translator could. But it does work in other languages, and the text is okay.
I did get too liberal with the translating the title, but just because it gives so well the idea behind "To Don't". I can roll it back today, no problem, just give me a signal, I have a free day!

**Pull request merged**
