### PR TITLE
Welcoming changes

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by CrazyMarvin** [comment]
Basically it is the same like the CoC I already copied into the repo. Your version is just a bit more unspecified. I don't think we have to update it but I will leave this open for some time to discuss it.

**Comment by comradekingu** [comment]
@CrazyMarvin
For what your intents were, laudable at that, yes. More than an order of magnitude shorter for "the same thing" sounds like this is just an issue of extreme bloat. (Made worse in version 2.0)

However, it differs in that there is no complexity, professionalism, authoritarianism, anti-humanity, poor writing, inept logic, and the system of meritocracy isn't challenged. The latter is a stated goal of its creator, and it is by the same person said to be political. Do note that the text-file has "political attacks" under "unacceptable behavior".

That is my full disclosure. I never believed in those things, not before the text-file, and not since. I have never pledged allegiance to it, and obviously respect your merit in doing with my contributions are you please.
That also means I respectfully stop contributing to projects that can't come up with a coherent reason for doing this, which so far is _zero_.

**Comment by CrazyMarvin** [comment]
Alright, I updated the code of conduct.

**Comment by comradekingu** [comment]
@CrazyMarvin It does not constitute a code of conduct though.
For

https://datatracker.ietf.org/doc/html/rfc2119
>SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

>Remember, contributions to this repository should follow its contributing guidelines and code of conduct. 

requires consideration, when it is in no such way self-aggrandising. That is a barrier to entry.
It is also not something to hide, though you could. This leads to dropping contributors because they think
it is a CoC. I don't write CoCs, and I don't want other people to accept or adopt it as such.

Edit: The README has
>Check out the contribution guidelines for details please.

When that is an empty document. https://github.com/Crazy-Marvin/ToDont/blob/trunk/.github/CONTRIBUTING.md

Nothing is actually better when all the green lights are on [x] this way.
I can write some guidelines if you want me to though.

Edit: Was able to contribute again, and fixed up some source strings.

**Pull request closed without merging**
